### ISSUE TITLE
Serialize/Deserialize does not work properly 

### ISSUE THREAD

**Issue by p4u** [noot/ring-go#2]
Serialize/Deserialize functions do not work.

Tested in "linkable" branch but should also fail in "master".

To reproduce the error, you can use this code:

```
package main

import (
	"fmt"
	"io/ioutil"
	"log"
	"os"
	"strconv"

	"github.com/ethereum/go-ethereum/crypto"
	"github.com/noot/ring-go/ring"
	"golang.org/x/crypto/sha3"
)

func main() {
	if len(os.Args) < 2 {
		fmt.Printf("Wrong ring size, use %s <size>\n", os.Args[0])
		os.Exit(1)
	}
	size, err := strconv.Atoi(os.Args[1])
	if err != nil {
		fmt.Printf("Wrong ring size, use %s <size>\n", os.Args[0])
		os.Exit(1)
	}
	fmt.Println("starting ring-go...")
	/* generate new private public keypair */
	privkey, err := crypto.HexToECDSA("358be44145ad16a1add8622786bef07e0b00391e072855a5667eb3c78b9d3803")
	if err != nil {
		log.Fatal(err)
	}

	/* sign message */
	file, err := ioutil.ReadFile("./message.txt")
	if err != nil {
		log.Fatal("could not read message from message.txt", err)
	}
	msgHash := sha3.Sum256(file)

	/* secret index */
	s := 7

	/* generate keyring */
	keyring := ring.GenNewKeyRing(size, privkey, s)

	/* sign */
	sig, err := ring.Sign(msgHash, keyring, privkey, s)
	if err != nil {
		log.Fatal(err)
	}

	byteSig := sig.SerializeSignature()
	fmt.Printf("Signature: %x\n", byteSig)
	fmt.Printf("Signature size: %d\n", sig.Size)
	fmt.Printf("Signature bytes: %d\n", len(byteSig))

	/* verify signature */
	sig2, err := ring.DeserializeSignature(byteSig)
	if err != nil {
		log.Println(err)
		panic("cannot deserialize signature")
	}
	ver := ring.Verify(sig2)
	fmt.Println("verified? ", ver)
}
```

Result:

With ring size = 10

```
Signature size: 10
Signature bytes: 1096
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x55bda0]

goroutine 1 [running]:
github.com/noot/ring-go/ring.Verify(0xc0000a6080, 0x448)
         go/src/github.com/noot/ring-go/ring/ring.go:315 +0x180
main.main()
        testing/ringct/ringct.go:62 +0x63a
exit status 2
```

With ring size = 100

```
Signature size: 100
Signature bytes: 9736
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x55bda0]

goroutine 1 [running]:
github.com/noot/ring-go/ring.Verify(0xc0000b2080, 0x2608)
        go/src/github.com/noot/ring-go/ring/ring.go:315 +0x180
main.main()
        testing/ringct/ringct.go:62 +0x63a
exit status 2
```

**Comment by noot** [comment]
Hey, I have fixed this bug in my latest commit: https://github.com/noot/ring-go/commit/152e6a9e99bf14383b8688a1b69c13158dc926e5#diff-48c6ca1c31515df4aa626d1dd5c3f9a3R122 Please try it with the updated code.  The issue was that I did not set the curve of the public key in the Deserialize function, which was causing the error when doing curve.ScalarMult. 

Also, I have changed the function signatures for Serialize and Deserialize, here is your code updated for that:
```
package main

import (
	"fmt"
	"io/ioutil"
	"log"
	"os"
	"strconv"

	"github.com/ethereum/go-ethereum/crypto"
	"github.com/noot/ring-go/ring"
	"golang.org/x/crypto/sha3"
)

func main() {
	if len(os.Args) < 2 {
		fmt.Printf("Wrong ring size, use %s <size>\n", os.Args[0])
		os.Exit(1)
	}

	size, err := strconv.Atoi(os.Args[1])
	if err != nil {
		fmt.Printf("Wrong ring size, use %s <size>\n", os.Args[0])
		os.Exit(1)
	}

	fmt.Println("starting ring-go...")
	/* generate new private public keypair */
	privkey, err := crypto.HexToECDSA("358be44145ad16a1add8622786bef07e0b00391e072855a5667eb3c78b9d3803")
	if err != nil {
		log.Fatal(err)
	}

	/* sign message */
	file, err := ioutil.ReadFile("./message.txt")
	if err != nil {
		log.Fatal("could not read message from message.txt", err)
	}
	msgHash := sha3.Sum256(file)

	/* secret index */
	s := 7

	/* generate keyring */
	keyring, err := ring.GenNewKeyRing(size, privkey, s)
	if err != nil {
		log.Fatal(err)
	}

	/* sign */
	sig, err := ring.Sign(msgHash, keyring, privkey, s)
	if err != nil {
		log.Fatal(err)
	}

	byteSig, err := sig.Serialize()
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("Signature: %x\n", byteSig)
	fmt.Printf("Signature size: %d\n", sig.Size)
	fmt.Printf("Signature bytes: %d\n", len(byteSig))

	/* verify signature */
	sig2, err := ring.Deserialize(byteSig)
	if err != nil {
		log.Println(err)
		panic("cannot deserialize signature")
	}
	fmt.Println(sig2.Size)

	ver := ring.Verify(sig2)
	fmt.Println("verified? ", ver)
}
```

**Comment by p4u** [comment]
Thank you, it works now!
